import importlib.util
from pathlib import Path
from typing import TYPE_CHECKING, cast

import pytest

if TYPE_CHECKING:
    from collections.abc import Callable

# Built from parts so the public-release audit does not see real addresses.
_ANTHROPIC = "anthropic" + ".com"
_NOUS = "nousresearch" + ".com"
_LOCAL_HOST = "fedora" + ".local"

_SCRIPT = Path(__file__).parents[1] / ".github" / "scripts" / "attribution_check.py"
_SPEC = importlib.util.spec_from_file_location("attribution_check", _SCRIPT)
assert _SPEC is not None
assert _SPEC.loader is not None
attribution_check = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(attribution_check)

branch_problem = cast("Callable[[str], str | None]", attribution_check.branch_problem)
is_agent_identity = cast("Callable[[str], bool]", attribution_check.is_agent_identity)
check_text = cast(
    "Callable[[str, str | None], list[str]]", attribution_check.check_text
)


@pytest.mark.parametrize(
    "name", ["feature/x", "dependabot/pip/x", "ci/attribution-check"]
)
def test_allowed_branch_names_pass(name: str) -> None:
    assert branch_problem(name) is None


@pytest.mark.parametrize(
    "name", ["claude/x", "mwd/x", "feature/Bad", "feature/", "main"]
)
def test_other_branch_names_fail_with_the_message(name: str) -> None:
    assert branch_problem(name) == (
        f"branch '{name}' must be <type>/<slug> with type feature, bugfix, "
        "hotfix, docs, chore, refactor, ci or test"
    )


@pytest.mark.parametrize(
    "identity",
    [
        f"Claude <noreply@{_ANTHROPIC}>",
        f"Claude Opus 4.5 <noreply@{_ANTHROPIC}>",
        f"Codex <codex@{_LOCAL_HOST}>",
        "Hermes Agent <someone@example.com>",
        f"Someone <hermes@{_NOUS}>",
        "chatgpt-codex-connector[bot] <x@example.com>",
    ],
)
def test_agent_identities_are_flagged(identity: str) -> None:
    assert is_agent_identity(identity)


@pytest.mark.parametrize(
    "identity",
    [
        "Jane Doe <jane@example.com>",
        f"Jane Doe <jane@{_ANTHROPIC}>",
        f"Jane Doe <jane@{_NOUS}>",
        "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
        "Claude Dupont <claude@example.com>",
        "Codex Smith <smith@example.com>",
    ],
)
def test_people_are_not_flagged(identity: str) -> None:
    assert not is_agent_identity(identity)


@pytest.mark.parametrize(
    "text",
    [
        "Generated by Codex",
        "Generated with [Claude Code](https://x)",
        "Co-Authored-By: Hermes Agent <a@example.com>",
        "Claude-Session: https://claude.ai/code/session_x",
    ],
)
def test_attribution_text_is_flagged(text: str) -> None:
    assert check_text("body", text)


def test_human_co_author_is_not_flagged() -> None:
    assert not check_text("body", "Co-Authored-By: Claude Dupont <c@example.com>")
